"""Add remembered_facts column to users table

Revision ID: 43634ef2ee7f
Revises: 
Create Date: 2025-04-05 00:58:12.243803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43634ef2ee7f'
down_revision: Union[str, None] = None # Reset to None as it's the only file
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually ###
    # Only add the missing column, assume 'users' table exists
    op.add_column('users', sa.Column('remembered_facts', sa.JSON(), nullable=True))
    # The following create_table and create_index commands were removed
    # as they were generated assuming the tables didn't exist.
    # If sessions table is also missing, a separate migration is needed.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually ###
    # Only drop the added column
    op.drop_column('users', 'remembered_facts')
    # The following drop_table and drop_index commands were removed.
    # ### end Alembic commands ###
